# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.CharField(max_length=50, unique=True)),
                ('a_end_description', models.CharField(blank=True, max_length=255)),
                ('b_end_description', models.CharField(blank=True, max_length=255)),
                ('circuit_type', models.CharField(blank=True, max_length=255)),
                ('circuit_info', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='catalogues.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Ne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, unique=True, verbose_name='FQDN')),
                ('nni_neighbors', models.ManyToManyField(blank=True, related_name='_ne_nni_neighbors_+', to='inventories.Ne')),
            ],
            options={
                'verbose_name_plural': 'Network Elements',
                'ordering': ['fqdn'],
                'verbose_name': 'Network Element',
            },
        ),
        migrations.CreateModel(
            name='OsCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['username'],
                'verbose_name': 'Operating System credentials',
            },
        ),
        migrations.AddField(
            model_name='ne',
            name='os_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.OsCredential', verbose_name='OS Credentials'),
        ),
    ]
