rman_network = {
    'edge1-dcu.nn.hea.net':  { 'hostname': 'edge1-dcu',
        'nni_neighbors': ['core1-dcu'],
    },
    'edge1-dcu-glasnevin.nn.hea.net': { 'hostname': 'edge1-dcu-glasnevin',
        'nni_neighbors': ['edge1-dcu', 'edge2-dcu'],
    },
    'edge1-dcu-spd.nn.hea.net': { 'hostname': 'edge1-dcu-spd',
        'nni_neighbors': ['edge1-dcu', 'edge2-dcu'],
    },
    'edge3-testlab.nn.hea.net': { 'hostname': 'edge3-testlab',
        'nni_neighbors': ['edge1-testlab', 'edge88-testlab'],
    },
    'dist1-itb.nn.hea.net': { 'hostname': 'dist1-itb',
        'nni_neighbors': ['core2-dcu', 'dist2-itb'],
    },
    'dist2-itb.nn.hea.net': { 'hostname': 'dist2-itb',
        'nni_neighbors': ['core1-blanch', 'dist1-itb'],
    },
    'rr1-cwt.nn.hea.net': { 'hostname': 'rr1-cwt',
        'nni_neighbors': ['core1-cwt', 'core2-cwt'],
    },
}
