# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthernetPhysicalLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Manufacturer name')),
            ],
            options={
                'verbose_name_plural': 'Ethernet Physical Layer Specifications',
                'ordering': ['name'],
                'verbose_name': 'Ethernet Physical Layer',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Manufacturer name')),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer abbreviation')),
            ],
            options={
                'verbose_name_plural': 'OEMs (Original Equipment Manufacturers)',
                'ordering': ['name'],
                'verbose_name': 'OEM (Original Equipment Manufacturer)',
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255, verbose_name='OS Family')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Operating Systems',
                'ordering': ['manufacturer'],
                'verbose_name': 'Operating Sytem',
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255, unique=True, verbose_name='Part Number')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogues.Manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Part Numbers',
                'ordering': ['part_number'],
                'verbose_name': 'Part Number',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setting for Type/Cable Type configuration')),
                ('powerbudget', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Power budget, delta between Transmit Min. and Receive Min.')),
                ('receive_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimum dBm tolerated on receive')),
                ('receive_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Maximum dBm tolerated on receive')),
            ],
            options={
                'verbose_name_plural': 'Transceivers',
                'ordering': ['part_number'],
                'verbose_name': 'Transceiver',
            },
        ),
        migrations.CreateModel(
            name='TransceiverFormFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Form factor')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transceiver Form Factors',
                'ordering': ['name'],
                'verbose_name': 'Transceiver Form Factor',
            },
        ),
        migrations.AddField(
            model_name='transceiver',
            name='form_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogues.TransceiverFormFactor', verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='transceiver',
            name='part_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogues.PartNumber', verbose_name='Part Number'),
        ),
    ]
